### ISSUE TITLE
Auto Closing Popup when the calendar is being clicked

### ISSUE THREAD

**Issue by penton-astro** [adamalbrecht/ngQuickDate#96]
Hi,

Previously, this directive was working fine. However, recently it goes heir wire. 

The issue is, when you click at the calendar and expect the calendar pop up to display, it just goes missing. The following are the reproducing steps:

1) Go to http://adamalbrecht.github.io/ngQuickDate/
2) Click at the calendar below "Basic datepicker set to"
3) Observe that the calendar popup display for a while then disappear.

**Comment by tregoning** [comment]
Actually I would suggest you remove ng-click instead otherwise it would not be as keyboard friendly.

**Comment by penton-astro** [comment]
Mind to be more specific?


Nothing in this communication shall constitute a legally binding offer, or agreement. A legally binding offer or agreement may only arise in an instance where a contract is executed (in duplicate) by an authorized officer of the  Company and an authorized officer of the counterparty(ies) subsequent to relevant approvals from the Company's senior management.

This message is intended only for the ordinary use by the person to whom it is addressed and may contain information that is confidential and privileged under applicable laws, or otherwise protected by work product immunity or other legal rules. No one else may copy or forward all or any of it in any form. If you are not the intended recipient, you are hereby notified that any use, review or disclosure or copying of this message and information it contains is prohibited. If you have received this message in error, please notify the sender by reply e-mail and then delete it from your system. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Astro Malaysia Holdings Berhad (932533-V), Astro Overseas Limited (27692 / 994016-A) and all its subsidiaries. Thank you.
